"""Declarative reaction registry for ``historical_2020`` through M4B.

The registry describes individual processes but does not assemble tendencies,
solve QSSA equations, or integrate a state vector.  That boundary is deliberate:
those operations belong to later milestones.
"""

from __future__ import annotations

from dataclasses import dataclass

from tfm_photochem.metadata import Parameter

from .config import CONFIGURATION, IMPLEMENTED_COEFFICIENT, PENDING_INPUT
from .kinetics import RATE_LAWS

Stoichiometry = tuple[tuple[str, float], ...]


@dataclass(frozen=True)
class Reaction:
    """One auditable chemical, photolytic, or radiative process."""

    identifier: str
    equation: str
    reactants: Stoichiometry
    products: Stoichiometry
    reaction_type: str
    modifies: tuple[str, ...]
    coefficient_id: str | None
    coefficient_unit: str
    status: str
    reference: str
    year: int
    configuration: str
    provenance_note: str
    li2020_link: str
    efficiency_id: str | None = None


LI2020 = "Li et al., Atmospheric Measurement Techniques 13 (2020)"
JPL18 = "JPL Publication 15-10, Evaluation 18"
BS2005 = "Brasseur and Solomon (2005), Aeronomy of the Middle Atmosphere"

SCALAR_PARAMETERS = {
    "yield_o3_hartley_delta_o1d": Parameter(
        0.9,
        "1",
        f"{LI2020}, Table A1",
        2020,
        CONFIGURATION,
        "Product-channel yield for direct Delta and O1D production; it must not scale the future total O3 photolysis loss.",
    ),
    "yield_o2_lya_o1d": Parameter(
        0.44,
        "1",
        f"{LI2020}, Table A1",
        2020,
        CONFIGURATION,
        "Product-channel yield for Lyman-alpha O1D production; it must not scale the future total O2 photolysis loss.",
    ),
    "branch_o1d_o2_b1": Parameter(
        0.8,
        "1",
        f"{LI2020}, Table A1, Q1a",
        2020,
        CONFIGURATION,
        "Li routing to B1 retained exactly; total O1D+O2 coefficient is from JPL18.",
    ),
    "branch_o1d_o2_b0": Parameter(
        0.2,
        "1",
        f"{LI2020}, Table A1, Q1b",
        2020,
        CONFIGURATION,
        "Li routing to B0 retained exactly; branches sum to unity.",
    ),
    "barth_c_o2": Parameter(
        6.6,
        "1",
        "McDade et al. (1986), as adopted by Li et al. (2020)",
        1986,
        CONFIGURATION,
        "Empirical effective-mechanism coefficient; not an elementary rate law.",
    ),
    "barth_c_o": Parameter(
        19.0,
        "1",
        "McDade et al. (1986), as adopted by Li et al. (2020)",
        1986,
        CONFIGURATION,
        "Empirical effective-mechanism coefficient; not an elementary rate law.",
    ),
}


def _reaction(
    identifier: str,
    equation: str,
    reactants: Stoichiometry,
    products: Stoichiometry,
    reaction_type: str,
    modifies: tuple[str, ...],
    coefficient_id: str | None,
    reference: str,
    year: int,
    provenance_note: str,
    li2020_link: str,
    *,
    efficiency_id: str | None = None,
    pending_unit: str = "s^-1",
) -> Reaction:
    if coefficient_id is None:
        unit = pending_unit
        status = PENDING_INPUT
    else:
        unit = RATE_LAWS[coefficient_id].unit
        status = IMPLEMENTED_COEFFICIENT
    return Reaction(
        identifier=identifier,
        equation=equation,
        reactants=reactants,
        products=products,
        reaction_type=reaction_type,
        modifies=modifies,
        coefficient_id=coefficient_id,
        coefficient_unit=unit,
        status=status,
        reference=reference,
        year=year,
        configuration=CONFIGURATION,
        provenance_note=provenance_note,
        li2020_link=li2020_link,
        efficiency_id=efficiency_id,
    )


R = _reaction
_LI_TOPOLOGY = "Li 2020 Sect. 2.3 and Table A1"
_FROZEN_HOX = "Frozen TFM historical_2020 HOx topology; JPL18 coefficient"

REACTIONS = (
    R(
        "O_ASSOCIATION",
        "O + O2 + M -> O3 + M",
        (("O", 1), ("O2", 1), ("M", 1)),
        (("O3", 1), ("M", 1)),
        "termolecular",
        ("O", "O3"),
        "k_o_o2_m",
        JPL18,
        2015,
        "JPL18 Table 2-1 low-pressure-limit coefficient.",
        "Supports the O/O3 chemistry linked to Li's airglow topology.",
    ),
    R(
        "O_O3",
        "O + O3 -> 2 O2",
        (("O", 1), ("O3", 1)),
        (("O2", 2),),
        "bimolecular",
        ("O", "O3"),
        "k_o_o3",
        JPL18,
        2015,
        "JPL18 Table 1A, Ox A1.",
        "Supports the O/O3 chemistry linked to Li's airglow topology.",
    ),
    R(
        "BARTH_RECOMBINATION",
        "2 O + M -> O2star + M",
        (("O", 2), ("M", 1)),
        (("O2star", 1), ("M", 1)),
        "termolecular",
        ("O", "O2star"),
        "k_o_o_m_barth",
        BS2005,
        2005,
        "Li Table A1 prints exp(300/T); historical sources give (300/T)^2. This is the same recombination event as the O+O+M kinetic shorthand and is not double-counted.",
        "Li 2020 Table A1, Barth.",
    ),
    R(
        "H_O2_ASSOCIATION",
        "H + O2 + M -> HO2 + M",
        (("H", 1), ("O2", 1), ("M", 1)),
        (("HO2", 1), ("M", 1)),
        "termolecular",
        ("H", "HO2"),
        "k_h_o2_m",
        JPL18,
        2015,
        "JPL18 Table 2-1, HOx B1 low-pressure limit.",
        _FROZEN_HOX,
    ),
    R(
        "H_O3",
        "H + O3 -> OH + O2",
        (("H", 1), ("O3", 1)),
        (("OH", 1), ("O2", 1)),
        "bimolecular",
        ("H", "O3", "OH"),
        "k_h_o3",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B4.",
        _FROZEN_HOX,
    ),
    R(
        "O_OH",
        "O + OH -> O2 + H",
        (("O", 1), ("OH", 1)),
        (("O2", 1), ("H", 1)),
        "bimolecular",
        ("O", "OH", "H"),
        "k_o_oh",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B1.",
        _FROZEN_HOX,
    ),
    R(
        "O_HO2",
        "O + HO2 -> OH + O2",
        (("O", 1), ("HO2", 1)),
        (("OH", 1), ("O2", 1)),
        "bimolecular",
        ("O", "HO2", "OH"),
        "k_o_ho2",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B2.",
        _FROZEN_HOX,
    ),
    R(
        "OH_O3",
        "OH + O3 -> HO2 + O2",
        (("OH", 1), ("O3", 1)),
        (("HO2", 1), ("O2", 1)),
        "bimolecular",
        ("OH", "O3", "HO2"),
        "k_oh_o3",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B6.",
        _FROZEN_HOX,
    ),
    R(
        "HO2_O3",
        "HO2 + O3 -> OH + 2 O2",
        (("HO2", 1), ("O3", 1)),
        (("OH", 1), ("O2", 2)),
        "bimolecular",
        ("HO2", "O3", "OH"),
        "k_ho2_o3",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B12.",
        _FROZEN_HOX,
    ),
    R(
        "OH_H2",
        "OH + H2 -> H2O + H",
        (("OH", 1), ("H2", 1)),
        (("H2O", 1), ("H", 1)),
        "bimolecular",
        ("OH", "H"),
        "k_oh_h2",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B7.",
        _FROZEN_HOX,
    ),
    R(
        "H_HO2_2OH",
        "H + HO2 -> 2 OH",
        (("H", 1), ("HO2", 1)),
        (("OH", 2),),
        "bimolecular",
        ("H", "HO2", "OH"),
        "k_h_ho2_2oh",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B5 first channel.",
        _FROZEN_HOX,
    ),
    R(
        "H_HO2_H2O_O",
        "H + HO2 -> H2O + O",
        (("H", 1), ("HO2", 1)),
        (("H2O", 1), ("O", 1)),
        "bimolecular",
        ("H", "HO2", "O"),
        "k_h_ho2_h2o_o",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B5 second channel.",
        _FROZEN_HOX,
    ),
    R(
        "H_HO2_H2_O2",
        "H + HO2 -> H2 + O2",
        (("H", 1), ("HO2", 1)),
        (("H2", 1), ("O2", 1)),
        "bimolecular",
        ("H", "HO2"),
        "k_h_ho2_h2_o2",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B5 third channel.",
        _FROZEN_HOX,
    ),
    R(
        "OH_OH",
        "2 OH -> H2O + O",
        (("OH", 2),),
        (("H2O", 1), ("O", 1)),
        "bimolecular",
        ("OH", "O"),
        "k_oh_oh",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B9.",
        _FROZEN_HOX,
    ),
    R(
        "OH_HO2",
        "OH + HO2 -> H2O + O2",
        (("OH", 1), ("HO2", 1)),
        (("H2O", 1), ("O2", 1)),
        "bimolecular",
        ("OH", "HO2"),
        "k_oh_ho2",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B10.",
        _FROZEN_HOX,
    ),
    R(
        "HO2_HO2",
        "2 HO2 -> H2O2 + O2",
        (("HO2", 2),),
        (("H2O2", 1), ("O2", 1)),
        "bimolecular",
        ("HO2", "H2O2"),
        "k_ho2_ho2",
        JPL18,
        2015,
        "JPL18 Table 1B, HOx B13; effective second-order coefficient includes M. The separate water-complex enhancement is outside the frozen baseline.",
        _FROZEN_HOX,
    ),
    R(
        "OH_H2O2",
        "OH + H2O2 -> H2O + HO2",
        (("OH", 1), ("H2O2", 1)),
        (("H2O", 1), ("HO2", 1)),
        "bimolecular",
        ("OH", "H2O2", "HO2"),
        "k_oh_h2o2",
        JPL18,
        2015,
        "JPL18 Note B11, 200-300 K recommendation.",
        _FROZEN_HOX,
    ),
    R(
        "H2O2_PHOTOLYSIS",
        "H2O2 + photon -> 2 OH",
        (("H2O2", 1), ("photon", 1)),
        (("OH", 2),),
        "photolysis",
        ("H2O2", "OH"),
        None,
        JPL18,
        2015,
        "PENDING INPUT: historical H2O2 cross sections, quantum yields, and spectral radiation are not bundled.",
        "Frozen HOx topology; numerical photolysis input deferred.",
    ),
    R(
        "H2O_PHOTOLYSIS_A",
        "H2O + photon -> H + OH",
        (("H2O", 1), ("photon", 1)),
        (("H", 1), ("OH", 1)),
        "photolysis",
        ("H", "OH"),
        None,
        JPL18,
        2015,
        "PENDING INPUT: historical H2O cross sections/channel yield and spectral radiation are not bundled.",
        "Frozen HOx topology; J_H2O_a input deferred.",
    ),
    R(
        "H2O_PHOTOLYSIS_B",
        "H2O + photon -> H2 + O1D",
        (("H2O", 1), ("photon", 1)),
        (("H2", 1), ("O1D", 1)),
        "photolysis",
        ("O1D",),
        None,
        JPL18,
        2015,
        "PENDING INPUT: historical H2O cross sections/channel yield and spectral radiation are not bundled.",
        "Frozen HOx topology; J_H2O_b input deferred.",
    ),
    R(
        "O3_HARTLEY",
        "O3 + photon -> Delta + O1D",
        (("O3", 1), ("photon", 1)),
        (("Delta", 1), ("O1D", 1)),
        "photolysis",
        ("O3", "Delta", "O1D"),
        None,
        f"{LI2020}; {JPL18}; historical cross sections pending",
        2015,
        "PENDING INPUT: JH remains injected. This registry row is the actual reduced 0.9 excited channel; its gross JH*O3 value is diagnostic only.",
        "Li 2020 Table A1 supplies the airglow channel; M4B embeds it in a complete total-O3 budget.",
        efficiency_id="yield_o3_hartley_delta_o1d",
    ),
    R(
        "O3_PHOTOLYSIS_GROUND_EFFECTIVE",
        "O3 + photon -> O2 + O",
        (("O3", 1), ("photon", 1)),
        (("O2", 1), ("O", 1)),
        "photolysis",
        ("O3", "O"),
        None,
        f"Anqi Li thesis (2017), Sect. 3.2 Eq. 3.7; {BS2005}, Sect. 5.2.1; {JPL18} excited-state yield",
        2017,
        "PENDING INPUT: J_O3_TOTAL remains injected. M4B derives the effective complement J_O3_TOTAL - 0.9*JH; this reduced row is not from Li 2020 Table A1.",
        "M4B corrective Chapman/odd-oxygen closure, outside Li 2020's airglow-only Table A1.",
    ),
    R(
        "O2_SRC",
        "O2 + photon(SRC) -> O + O1D",
        (("O2", 1), ("photon", 1)),
        (("O", 1), ("O1D", 1)),
        "photolysis",
        ("O", "O1D"),
        None,
        f"{LI2020}; historical cross sections pending",
        2020,
        "PENDING INPUT: Schumann-Runge continuum calculation is outside M2; this is a distinct spectral channel from O2_LYMAN_ALPHA.",
        "Li 2020 Table A1, Jsrc.",
    ),
    R(
        "O2_LYMAN_ALPHA",
        "O2 + photon(Lyman-alpha) -> O + O1D",
        (("O2", 1), ("photon", 1)),
        (("O", 1), ("O1D", 1)),
        "photolysis",
        ("O", "O1D"),
        None,
        f"{LI2020}; historical cross sections pending",
        2020,
        "PENDING INPUT: Lyman-alpha spectral calculation is outside M2; 0.44 efficiency is registered. This is a distinct spectral channel from O2_SRC.",
        "Li 2020 Table A1, JLalpha.",
        efficiency_id="yield_o2_lya_o1d",
    ),
    R(
        "O2_PHOTOLYSIS_GROUND_EFFECTIVE",
        "O2 + photon -> 2 O",
        (("O2", 1), ("photon", 1)),
        (("O", 2),),
        "photolysis",
        ("O",),
        None,
        f"Anqi Li thesis (2017), Sect. 3.2 Eq. 3.4; {BS2005}, Sect. 5.2.1; {JPL18} excited-state yield",
        2017,
        "PENDING INPUT: J_O2_TOTAL remains injected. M4B derives the effective complement J_O2_TOTAL - J_SRC - 0.44*J_LYA; this reduced row is not from Li 2020 Table A1.",
        "M4B corrective Chapman/odd-oxygen closure, outside Li 2020's airglow-only Table A1.",
    ),
    R(
        "O2_A_BAND",
        "O2 + photon(A-band) -> B0",
        (("O2", 1), ("photon", 1)),
        (("B0", 1),),
        "excitation",
        ("B0",),
        None,
        "HITRAN historical data cited by Li et al. (2020)",
        2017,
        "PENDING INPUT: gA requires a reproducible historical HITRAN line dataset and radiative transfer.",
        "Li 2020 Table A1, gA.",
    ),
    R(
        "O2_B_BAND",
        "O2 + photon(B-band) -> B1",
        (("O2", 1), ("photon", 1)),
        (("B1", 1),),
        "excitation",
        ("B1",),
        None,
        "HITRAN historical data cited by Li et al. (2020)",
        2017,
        "PENDING INPUT: gB requires a reproducible historical HITRAN line dataset and radiative transfer.",
        "Li 2020 Table A1, gB.",
    ),
    R(
        "O2_IRA_BAND",
        "O2 + photon(IRA-band) -> Delta",
        (("O2", 1), ("photon", 1)),
        (("Delta", 1),),
        "excitation",
        ("Delta",),
        None,
        "HITRAN historical data cited by Li et al. (2020)",
        2017,
        "PENDING INPUT: gIRA requires a reproducible historical HITRAN line dataset and radiative transfer.",
        "Li 2020 Table A1, gIRA.",
    ),
    R(
        "O1D_RADIATIVE",
        "O1D -> O + photon(630 nm)",
        (("O1D", 1),),
        (("O", 1), ("photon", 1)),
        "radiative",
        ("O1D", "O"),
        "a_o1d",
        LI2020,
        2020,
        "Li 2020 Table A1, A1.",
        "Li 2020 A1.",
    ),
    R(
        "B0_RADIATIVE",
        "B0 -> O2 + photon(762 nm)",
        (("B0", 1),),
        (("O2", 1), ("photon", 1)),
        "radiative",
        ("B0",),
        "a_b0",
        LI2020,
        2020,
        "Li 2020 Table A1, A2.",
        "Li 2020 A2.",
    ),
    R(
        "B1_RADIATIVE",
        "B1 -> O2 + photon(771 nm)",
        (("B1", 1),),
        (("O2", 1), ("photon", 1)),
        "radiative",
        ("B1",),
        "a_b1",
        LI2020,
        2020,
        "Li's printed equation leaves B1 unchanged, but Sect. 2.3 defines A3 as inverse lifetime returning the state to ground; registry records that explicit loss topology.",
        "Li 2020 A3.",
    ),
    R(
        "DELTA_RADIATIVE",
        "Delta -> O2 + photon(1.27 micrometre)",
        (("Delta", 1),),
        (("O2", 1), ("photon", 1)),
        "radiative",
        ("Delta",),
        "a_delta",
        LI2020,
        2020,
        "Li Table A1 typesets 1.24 micrometres; its text, gIRA definition, and TFM observable identify the 1.27 micrometre band.",
        "Li 2020 A4.",
    ),
    R(
        "O1D_N2",
        "O1D + N2 -> O + N2",
        (("O1D", 1), ("N2", 1)),
        (("O", 1), ("N2", 1)),
        "quenching",
        ("O1D", "O"),
        "k_o1d_n2",
        JPL18,
        2015,
        "JPL18 Table 1A A7 gives exp(+110/T); Li prints exp(-110/T).",
        "Li 2020 Q1.",
    ),
    R(
        "O1D_O2_B1",
        "O1D + O2 -> O + B1",
        (("O1D", 1), ("O2", 1)),
        (("O", 1), ("B1", 1)),
        "quenching",
        ("O1D", "O", "B1"),
        "k_o1d_o2",
        JPL18,
        2015,
        "JPL18 total coefficient gives exp(+55/T); Li prints exp(-55/T). Li's 0.8 B1 routing is retained.",
        "Li 2020 Q1a.",
        efficiency_id="branch_o1d_o2_b1",
    ),
    R(
        "O1D_O2_B0",
        "O1D + O2 -> O + B0",
        (("O1D", 1), ("O2", 1)),
        (("O", 1), ("B0", 1)),
        "quenching",
        ("O1D", "O", "B0"),
        "k_o1d_o2",
        JPL18,
        2015,
        "JPL18 total coefficient gives exp(+55/T); Li prints exp(-55/T). Li's 0.2 B0 routing is retained.",
        "Li 2020 Q1b.",
        efficiency_id="branch_o1d_o2_b0",
    ),
    R(
        "O1D_H2O",
        "O1D + H2O -> 2 OH",
        (("O1D", 1), ("H2O", 1)),
        (("OH", 2),),
        "bimolecular",
        ("O1D", "OH"),
        "k_o1d_h2o",
        JPL18,
        2015,
        "JPL18 Table 1A A6; dominant channel.",
        "Frozen O1D QSSA topology; coefficient from JPL18.",
    ),
    R(
        "O1D_H2",
        "O1D + H2 -> H + OH",
        (("O1D", 1), ("H2", 1)),
        (("H", 1), ("OH", 1)),
        "bimolecular",
        ("O1D", "H", "OH"),
        "k_o1d_h2",
        JPL18,
        2015,
        "JPL18 Table 1A A5; dominant channel.",
        "Frozen O1D QSSA topology; coefficient from JPL18.",
    ),
    R(
        "B1_O2",
        "B1 + O2 -> B0 + O2",
        (("B1", 1), ("O2", 1)),
        (("B0", 1), ("O2", 1)),
        "quenching",
        ("B1", "B0"),
        "k_b1_o2",
        LI2020,
        2020,
        "Li Table A1 Q2a adoption via the Yankovsky et al. (2016) reference compilation; O2 vibrational excitation in the collider is not an explicit model species.",
        "Li 2020 Q2a.",
    ),
    R(
        "B1_N2",
        "B1 + N2 -> B0 + N2",
        (("B1", 1), ("N2", 1)),
        (("B0", 1), ("N2", 1)),
        "quenching",
        ("B1", "B0"),
        "k_b1_n2",
        LI2020,
        2020,
        "Li Table A1 Q2a adoption via the Yankovsky et al. (2016) reference compilation.",
        "Li 2020 Q2a.",
    ),
    R(
        "B1_O",
        "B1 + O -> O2 + O",
        (("B1", 1), ("O", 1)),
        (("O2", 1), ("O", 1)),
        "quenching",
        ("B1",),
        "k_b1_o",
        LI2020,
        2020,
        "Li Table A1 Q2a adoption via the Yankovsky et al. (2016) reference compilation.",
        "Li 2020 Q2a.",
    ),
    R(
        "B1_O3",
        "B1 + O3 -> 2 O2 + O",
        (("B1", 1), ("O3", 1)),
        (("O2", 2), ("O", 1)),
        "quenching",
        ("B1", "O3", "O"),
        "k_b1_o3",
        LI2020,
        2020,
        "Li Table A1 Q2a adoption via the Yankovsky et al. (2016) reference compilation.",
        "Li 2020 Q2a.",
    ),
    R(
        "B0_N2",
        "B0 + N2 -> Delta + N2",
        (("B0", 1), ("N2", 1)),
        (("Delta", 1), ("N2", 1)),
        "quenching",
        ("B0", "Delta"),
        "k_b0_n2",
        JPL18,
        2015,
        "JPL18 A86 total temperature-dependent coefficient. Delta production is the simplified Li 2020 routing assumption.",
        "Li 2020 Q2b.",
    ),
    R(
        "B0_O2",
        "B0 + O2 -> Delta + O2",
        (("B0", 1), ("O2", 1)),
        (("Delta", 1), ("O2", 1)),
        "quenching",
        ("B0", "Delta"),
        "k_b0_o2",
        JPL18,
        2015,
        "JPL18 A81; Delta yield approximately unity.",
        "Li 2020 Q2b.",
    ),
    R(
        "B0_O",
        "B0 + O -> Delta + O",
        (("B0", 1), ("O", 1)),
        (("Delta", 1), ("O", 1)),
        "quenching",
        ("B0", "Delta"),
        "k_b0_o",
        LI2020,
        2020,
        "Li assumes Delta product; JPL18 A80 tabulates total loss.",
        "Li 2020 Q2b.",
    ),
    R(
        "B0_O3",
        "B0 + O3 -> Delta + O3",
        (("B0", 1), ("O3", 1)),
        (("Delta", 1), ("O3", 1)),
        "quenching",
        ("B0", "Delta"),
        "k_b0_o3",
        JPL18,
        2015,
        "JPL18 A82 supplies the total temperature-dependent B0-loss coefficient. B0 + O3 -> Delta + O3 is the simplified Li 2020 model-routing assumption; it is not a claim that JPL assigns 100 percent of the total to this channel, and no unapproved branching is introduced.",
        "Li 2020 Q2b.",
    ),
    R(
        "B0_CO2",
        "B0 + CO2 -> Delta + CO2",
        (("B0", 1), ("CO2", 1)),
        (("Delta", 1), ("CO2", 1)),
        "quenching",
        ("B0", "Delta"),
        "k_b0_co2",
        JPL18,
        2015,
        "JPL18 A88; Delta yield >=90 percent.",
        "Li 2020 Q2b.",
    ),
    R(
        "DELTA_O2",
        "Delta + O2 -> 2 O2",
        (("Delta", 1), ("O2", 1)),
        (("O2", 2),),
        "quenching",
        ("Delta",),
        "k_delta_o2",
        JPL18,
        2015,
        "JPL18 A74.",
        "Li 2020 Q3.",
    ),
    R(
        "DELTA_N2",
        "Delta + N2 -> O2 + N2",
        (("Delta", 1), ("N2", 1)),
        (("O2", 1), ("N2", 1)),
        "quenching",
        ("Delta",),
        "k_delta_n2",
        JPL18,
        2015,
        "JPL18 A78 is an upper limit; Li uses its boundary magnitude.",
        "Li 2020 Q3.",
    ),
    R(
        "DELTA_O",
        "Delta + O -> O2 + O",
        (("Delta", 1), ("O", 1)),
        (("O2", 1), ("O", 1)),
        "quenching",
        ("Delta",),
        "k_delta_o",
        JPL18,
        2015,
        "JPL18 A73 is an upper limit; Li uses its boundary magnitude.",
        "Li 2020 Q3.",
    ),
    R(
        "DELTA_O3",
        "Delta + O3 -> O + 2 O2",
        (("Delta", 1), ("O3", 1)),
        (("O", 1), ("O2", 2)),
        "quenching",
        ("Delta", "O3", "O"),
        "k_delta_o3",
        JPL18,
        2015,
        "Li prints Delta + O3 -> O2 + O3 with exp(+2840/T). JPL18 A75 gives Delta + O3 -> O + 2 O2 with exp(-2840/T); the registry adopts both the JPL topology and rate law. Future tendency consequence: -O3 and +O.",
        "Li 2020 Q3.",
    ),
    R(
        "BARTH_TRANSFER",
        "O2star + O2 -> B_unspecified + O2",
        (("O2star", 1), ("O2", 1)),
        (("B_unspecified", 1), ("O2", 1)),
        "excitation",
        ("O2star", "B_unspecified"),
        None,
        "McDade et al. (1986), effective mechanism used by Li et al. (2020)",
        1986,
        "PENDING INPUT at elementary-rate level: future algebra uses empirical C_O2=6.6 and C_O=19 rather than an invented transfer coefficient.",
        "Li 2020 Table A1, Barth transfer step.",
        pending_unit="cm^3 molecule^-1 s^-1",
    ),
    R(
        "BARTH_O2STAR_QUENCH",
        "O2star + M -> quenched_products + M",
        (("O2star", 1), ("M", 1)),
        (("quenched_products", 1), ("M", 1)),
        "quenching",
        ("O2star",),
        None,
        "McDade et al. (1986), effective mechanism used by Li et al. (2020)",
        1986,
        "PENDING INPUT at elementary-rate level: Li lists O, O2 and N2 losses without coefficients; future effective algebra uses registered empirical C values.",
        "Li 2020 Table A1, Barth loss step.",
        pending_unit="cm^3 molecule^-1 s^-1",
    ),
)

REACTION_BY_ID = {reaction.identifier: reaction for reaction in REACTIONS}
